#!/usr/bin/env node

const { Client } = require("pg");
const { createInterface } = require("node:readline");

function logAndExit(err) {
  console.log(err);
  process.exit(1);
} 



// This class handles all the user input and output
// This class depends on ExpenseData
class CLI {
  static HELP() {
    return `An expense recording system

Commands:

add AMOUNT MEMO [DATE] - record a new expense
clear - delete all expenses
list - list all expenses
delete NUMBER - remove expense with id NUMBER
search QUERY - list expenses with a matching memo field`
  }

  static displayHelp() {
    console.log(CLI.HELP());
  }

  constructor() {
    this.expenseData = new ExpenseData();
  }

  run(argsArr) {
    let command = argsArr[2];
    let args = argsArr.slice(3);

    if (command === undefined) {
      CLI.displayHelp();
    } else if (command === 'list') {
      this.expenseData.listExpenses();
    } else if (command === 'add') {
      if (args.length < 2) {
        console.log("You must provide an amount and memo.");
      } else {
        let [amount, memo] = args;
        this.expenseData.addExpense(amount, memo);
      }
    } else if (command === 'search') {
      this.expenseData.searchExpenses(args[0]);
    } else if (command === 'delete') {
      this.expenseData.deleteExpense(args[0]);
    } else if (command === 'clear') {
      let rl = createInterface({
        input: process.stdin,
        output: process.stdout
      })

      let questionText = 'This will remove all expenses. Are you sure? (enter y to confirm)';
      rl.question(questionText, (answer) => {
        if (answer === 'y') {
          this.expenseData.deleteAllExpenses();
        }
        rl.close();
      });
    }
  }
}


// This class handles all interaction with the database
// This class is dependent on node-postgres (the database stuffs)
class ExpenseData {
  constructor() {
    this.client = new Client({database: "expenses", password: "psql"});
  }

  async setupSchema() {
    let tableExistsQuery = `SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'expenses'`;
    let tableExistsQueryTwo = `SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'expenses')`;

    let tableCreationQuery = `CREATE TABLE expenses (
                                id serial PRIMARY KEY,
                                amount decimal(6, 2) NOT NULL,
                                memo text NOT NULL,
                                created_on DATE NOT NULL 
                              );`

    let res = await this.client.query(tableExistsQueryTwo).catch(err => logAndExit(err));
    
    if (!res.rows[0].exists) {
      await this.client.query(tableCreationQuery).catch(err => logAndExit(err));
    }
  }
  
  displayExpenses(rows) {
    rows.forEach(tuple => {
      //totalCost += Number(tuple.amount);
      let columns = [
        `${tuple.id}`.padStart(3),
        tuple.created_on.toDateString().padStart(12),
        Number(tuple.amount).toFixed(2).padStart(8),
        tuple.memo.trimStart()
      ];
      console.log(columns.join(` | `));
    });
  }

  displayCount(rowCount) {
    if (rowCount === 0) {
      console.log('There are no expenses.');
    } else if (rowCount === 1) {
      console.log('There is one expense:');
    } else {
      console.log(`There are ${rowCount} expenses:`);
    }
  }

  displayTotal(rows) {
    //calculate bar length and total expenses
    let total = 0;
    let maxLength = 0;
    rows.forEach(row => {
      total += Number(row.amount);
      let rowLength = 35 + row.memo.length;
      if (rowLength > maxLength) maxLength = rowLength;
    });

    //display the bar and total
    console.log("-".repeat(maxLength));
    console.log('Total' + String(total.toFixed(2)).padStart(27));
  }
  
  // list command
  async listExpenses() {
    await this.client.connect().catch(err => logAndExit(err));
    await this.setupSchema().catch(err => logAndExit(err));

    const res = await this.client.query('SELECT * FROM expenses ORDER BY created_on ASC')
                            .catch(err => logAndExit(err));

    this.displayCount(res.rowCount);
    if (res.rowCount > 0) this.displayExpenses(res.rows);
    if (res.rowCount > 1) this.displayTotal(res.rows);

    await this.client.end().catch(err => logAndExit(err));  
  }

  // add command
  async addExpense(amount, memo) {
    await this.client.connect().catch(err => logAndExit(err));
    await this.setupSchema().catch(err => logAndExit(err));

    let date = new Date();
    date = date.toLocaleDateString();

    let text = 'INSERT INTO expenses (amount, memo, created_on) VALUES ($1, $2, $3)';
    let values = [amount, memo, date];

    await this.client.query(text, values).catch(err => logAndExit(err));

    await this.client.end().catch(err => logAndExit(err));
  }

  // search command
  async searchExpenses(searchTerm) {
    await this.client.connect().catch(err => logAndExit(err));
    await this.setupSchema().catch(err => logAndExit(err));

    let text = `SELECT * FROM expenses WHERE memo ILIKE $1`;
    let params = [`%${searchTerm}%`];
    let res = await this.client.query(text, params).catch(err => logAndExit(err));

    this.displayCount(res.rowCount);
    if (res.rowCount > 0) this.displayExpenses(res.rows);
    if (res.rowCount > 1) this.displayTotal(res.rows);

    await this.client.end().catch(err => logAndExit(err));
  }

  //delete command
  async deleteExpense(id) {
    await this.client.connect().catch(err => logAndExit(err));
    await this.setupSchema().catch(err => logAndExit(err));

    let text = `DELETE FROM expenses WHERE id = $1 RETURNING *`;
    let res = await this.client.query(text, [id]).catch(err => logAndExit(err));
    
    if (res.rowCount === 0) {
      console.log(`There is no expense with the id '${id}'.`);
    } else {
      console.log(`The following expense has been deleted:`);
      this.displayExpenses(res.rows);
    }

    await this.client.end().catch(err => logAndExit(err));
  }
  
  // clear command
  async deleteAllExpenses() {
    await this.client.connect().catch(err => logAndExit(err));

    await this.client.query('DELETE FROM expenses')
                     .catch(err => logAndExit(err));

    console.log('All expenses have been deleted.');

    await this.client.end().catch(err => logAndExit(err));
  }
}

let cli = new CLI();
cli.run(process.argv);