#!/usr/bin/env node

const { Client } = require("pg");
const { argv } = require('node:process');
const client = new Client({database: "expenses", password: "psql"});

//logAndExit for promise handling
function logAndExit(err) {
  console.log(err);
  process.exit(1);
} 

// get the command and arguments from user input
// let command = argv[2];
// let args = argv.slice(3);


class CLI {
  static HELP() {
    return `An expense recording system

Commands:

add AMOUNT MEMO [DATE] - record a new expense
clear - delete all expenses
list - list all expenses
delete NUMBER - remove expense with id NUMBER
search QUERY - list expenses with a matching memo field`
  }

  static displayHelp() {
    console.log(CLI.HELP());
  }

  constructor() {
    this.expenseData = new ExpenseData();
  }

  run(argsArr) {
    let command = argsArr[2];
    let args = argsArr.slice(3);

    if (command === undefined) {
      CLI.displayHelp();
    } else if (command === 'list') {
      this.expenseData.displayList();
    } else if (command === 'add') {
      if (args.length < 2) {
        console.log("You must provide an amount and memo.");
      } else {
        let [amount, memo] = args;
        this.expenseData.addExpense(amount, memo);
      }
    } else if (command === 'clear') {
      clearExpenses();
    } else if (command === 'delete') {
      deleteExpense(args[0])
    }
  }
}


class ExpenseData {
  constructor() {
    this.client = new Client({database: "expenses", password: "psql"});
  }

  async displayList() {
    await client.connect()
                .catch(err => logAndExit(err));

    const data = await client.query('SELECT * FROM expenses ORDER BY created_on ASC')
                            .catch(err => logAndExit(err));

    displayFormattedData(data);
      
    await client.end()
                .catch(err => logAndExit(err));

    function displayFormattedData(data) {
      data.rows.forEach(tuple => {
        let columns = [
          `${tuple.id}`.padStart(3),
          tuple.created_on.toDateString().padStart(10),
          Number(tuple.amount).toFixed(2).padStart(8),
          tuple.memo
        ];

        console.log(columns.join(` | `));
      })
    }  
  }

  async addExpense(amount, memo) {
    await client.connect()
                .catch(err => logAndExit(err));

    let date = new Date();
    date = date.toLocaleDateString();

    let text = 'INSERT INTO expenses (amount, memo, created_on) VALUES ($1, $2, $3)';
    let values = [amount, memo, date];

    await client.query(text, values)
                .catch(err => logAndExit(err));

    await client.end()
                .catch(err => logAndExit(err));
  }
}

let commandLine = new CLI();
commandLine.run(argv);

// main command processing logic
// if (command === undefined) {
//   displayHelp();
// } else if (command === 'list') {
//   displayList();
// } else if (command === 'add') {
//   if (args.length < 2) {
//     console.log("You must provide an amount and memo.");
//   } else {
//     let [amount, memo] = args;
//     addExpense(amount, memo);
//   }
// } else if (command === 'clear') {
//   clearExpenses();
// } else if (command === 'delete') {
//   deleteExpense(args[0])
// }


// list command
// async function displayList() {
//   await client.connect()
//               .catch(err => logAndExit(err));

//   const data = await client.query('SELECT * FROM expenses ORDER BY created_on ASC')
//                            .catch(err => logAndExit(err));

//   displayFormattedData(data);
    
//   await client.end()
//               .catch(err => logAndExit(err));

//   function displayFormattedData(data) {
//     data.rows.forEach(tuple => {
//       let columns = [
//         `${tuple.id}`.padStart(3),
//         tuple.created_on.toDateString().padStart(10),
//         Number(tuple.amount).toFixed(2).padStart(8),
//         tuple.memo
//       ];

//       console.log(columns.join(` | `));
//     })
//   }  
//}

// help command
// function displayHelp() {
//     let output = `An expense recording system

// Commands:

// add AMOUNT MEMO [DATE] - record a new expense
// clear - delete all expenses
// list - list all expenses
// delete NUMBER - remove expense with id NUMBER
// search QUERY - list expenses with a matching memo field`;
  
//   console.log(output);
// };

//add command
// async function addExpense(amount, memo) {
//     await client.connect()
//                 .catch(err => logAndExit(err));

//     let date = new Date();
//     date = date.toLocaleDateString();

//     let text = 'INSERT INTO expenses (amount, memo, created_on) VALUES ($1, $2, $3)';
//     let values = [amount, memo, date];

//     await client.query(text, values)
//                 .catch(err => logAndExit(err));

//     await client.end()
//                 .catch(err => logAndExit(err));
// };

